AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  UsernameTag:
    Type: String
    Description: The team or group name to be used as the tag value
    Default: DsHackathonGroup1 # Make sure to update this tag value accourding to your group number

Resources:
  FlaskAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      CodeUri: ./
      Environment:
        Variables:
          FLASK_ENV: production
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonRDSFullAccess
      Tags:
        - Key: Username 
          Value: !Ref UsernameTag
      Events:
        WelcomeApiEvent:
          Type: Api
          Properties:
            Path: /welcome
            Method: GET
        GoodbyeApiEvent:
          Type: Api
          Properties:
            Path: /goodbye
            Method: GET
        HealthApiEvent:
          Type: Api
          Properties:
            Path: /health
            Method: GET
        # # Add your new api paths here
        # NewApiEvent:
        #   Type: Api
        #   Properties:
        #     Path: /newapi
        #     Method: GET

  # RDS Instance
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t4g.micro
      AllocatedStorage: 5
      Engine: postgres
      EngineVersion: "13.18"
      MasterUsername: hackathonuser
      MasterUserPassword: !Sub '{{resolve:ssm-secure:/hackathonuser/rds/password}}'
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt RDSSecurityGroup.GroupId
      Tags:
        - Key: Username 
          Value: !Ref UsernameTag

  # Security Group for RDS
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable database access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0  # Restrict to appropriate CIDR range or VPCy