AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  FlaskAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 30
      CodeUri: ./
      Environment:
        Variables:
          FLASK_ENV: production
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonAPIGatewayInvokeFullAccess
      Events:
        WelcomeApiEvent:
          Type: Api
          Properties:
            Path: /welcome
            Method: ANY
        GoodbyeApiEvent:
          Type: Api
          Properties:
            Path: /goodbye
            Method: ANY
